#!/bin/bash
awk 'BEGIN{split("water",a,"") for(i=1;i<=5;i++)c[a[i]]=i-1;W=ENVIRON["WATER"];for(i=1;i<=length(W);i++)x=x*5+c[substr(W,i,1)];split("stir.",a,"") for(i=1;i<=5;i++)c[a[i]]=i-1;S=ENVIRON["STIR"];for(i=1;i<=length(S);i++)y=y*5+c[substr(S,i,1)];z=x+y;split("bestchol",b,"") while(z){r=b[(z%9)+1] r;z=int(z/9)} print r}'
