#!/usr/bin/env bash
# Configures redirection for /redirect_me on a fresh Ubuntu server

set -e

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Add redirection config inside default server block
sed -i "/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-available/default

# Restart Nginx using service (not systemctl)
service nginx restart
